[package]
name = "hecs-play"
version = "0.1.0"
authors = ["Doug Hodson <doug@sidechannel.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hecs = "0.3.2"
rand = "0.8.3"
